# -*- coding: utf-8 -*-
"""ScoremeAssignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5cPK7hWCoQd179CdgkhsZYJEHfTtmPz
"""

!pip install pdf2docx
!pip install openpyxl
!pip install python-docx xlsxwriter

from google.colab import files

uploaded = files.upload()

from pdf2docx import Converter

def pdf_to_docx(pdf_file, docx_file):
    # Convert PDF to DOCX
    cv = Converter(pdf_file)
    cv.convert(docx_file, start=0, end=None)
    cv.close()

# List of PDF files to convert
pdf_files = ['test3.pdf', 'test5.pdf', 'test6.pdf']

# Process each PDF file
for pdf_file in pdf_files:
    if pdf_file in uploaded:
        # Generate output DOCX file path
        output_file = pdf_file.replace('.pdf', '.docx')
        # Convert PDF to DOCX
        pdf_to_docx(pdf_file, output_file)
        print(f"Converted {pdf_file} to {output_file}")
    else:
        print(f"{pdf_file} not uploaded.")

from google.colab import files

# List of converted DOCX files
docx_files = ['test3.docx', 'test5.docx', 'test6.docx']

# Download each DOCX file
for docx_file in docx_files:
  files.download(docx_file)

from openpyxl import Workbook
from openpyxl.styles import Alignment
from docx import Document
from google.colab import files

def docx_to_xlsx(docx_file, xlsx_file):
    # Load DOCX file
    doc = Document(docx_file)

    # Create a new Workbook
    wb = Workbook()

    # Remove default sheet created by Workbook and create a new one
    default_sheet = wb.active
    wb.remove(default_sheet)

    # Create a new sheet for the DOCX file
    ws = wb.create_sheet(title='Content')

    # Add headers if needed
    ws.append(['Text Content'])  # Example header

    # Iterate through paragraphs and add to Excel as rows
    for paragraph in doc.paragraphs:
        ws.append([paragraph.text])

    # Apply alignment to all cells
    for row in ws.iter_rows():
        for cell in row:
            cell.alignment = Alignment(wrap_text=True)

    # Save workbook as XLSX file
    wb.save(xlsx_file)
    print(f"Converted {docx_file} to {xlsx_file}")

# List of uploaded DOCX files
uploaded_files = ['test3.docx', 'test5.docx', 'test6.docx']

# Process each uploaded file
for docx_file in uploaded_files:
    # Generate output XLSX file path
    xlsx_file = docx_file.replace('.docx', '.xlsx')

    # Convert DOCX to XLSX
    docx_to_xlsx(docx_file, xlsx_file)

    # Download each converted XLSX file
    files.download(xlsx_file)

